sudo: required
services:
  - docker

before_install:
  - docker build -t "vasanth/docker-react" -f Dockerfile.dev .

script:
  - docker run -e CI=true vasanth/docker-react npm run test -- --coverage

